### ISSUE TITLE
支持快捷键嘛?

### ISSUE THREAD

**Issue by LouisLiu00** [xland/ScreenCapture#1]
如果要截取别的屏幕，软件在桌面上咋运行？
比如正在浏览器上，正在全屏观看视频等等...

**Comment by xland** [comment]
要做快捷键，就得做一个常驻在用户系统中得程序（服务进程）
这会让我们得截图工具变得复杂
不过我还在思考这个事情要不要做

目前来说，你可以参考这篇文章，自己注册个快捷键：
https://www.zhihu.com/question/450738311/answer/2635126508

**Comment by xland** [comment]
我在Readme里增加了如何设置快捷键的方法，目前来看使用情况还不错，
暂时先用这个方案了：
https://github.com/xland/ScreenCapture#hotkey

**Comment by chunlurenikun** [comment]
其实只需要创建一个快捷方式，右键快捷方式-属性-快捷键，就可以自定义启动快捷键了。不过在全屏播放视频或者游戏时好像会失效

**Comment by xland** [comment]
> 其实只需要创建一个快捷方式，右键快捷方式-属性-快捷键，就可以自定义启动快捷键了。不过在全屏播放视频或者游戏时好像会失效

这种办法响应会比较慢

**Comment by muwoo** [comment]
@LouisLiu00 @chunlurenikun 

我开发了一款 rubick 工具，集成了这个截图工具功能，ctrl+shift+A 快捷键可以快速使用，还可以安装orc插件使用截图orc功能哦：

rubick 官网：https://rubick.vip/

rubick 开源github 仓库：https://github.com/rubickCenter/rubick

![image](https://github.com/xland/ScreenCapture/assets/21073039/c1402e3f-3058-40e7-abc3-b738b6909722)
