### ISSUE TITLE
谢谢，能否实时显示截图大小

### ISSUE THREAD

**Issue by wzhq1997** [xland/ScreenCapture#10]
谢谢分享，很好用，能否有实时显示截图区域大小的功能。

**Comment by xland** [comment]
嗯~这个我先考虑一下
谢谢建议

**Comment by xland** [comment]
这个功能已经做好了，请下载最新版本测试，没啥问题的话，我过两天关闭这个issue

**Comment by wzhq1997** [comment]
非常感谢，已使用，没发现问题。再次感谢。
另外提了一个关于全屏时工具栏不显示的问题，见：[工具栏问题](https://github.com/xland/ScreenCapture/issues/15)。
