### ISSUE TITLE
测试发现用autohotkey启动会调用出几十个screencapture

### ISSUE THREAD

**Issue by huliyoudiangou** [xland/ScreenCapture#14]
win10专业版，22h2，19045.3324版本，测试发现用autohotkey启动会调用出几十个screencapture，是哪边的错误搞不清楚，使用的是screencapture0.2.5
![IMG_20230828_233727](https://github.com/xland/ScreenCapture/assets/75266067/7b8be955-6ae6-4375-8b8e-df9acb2757d6)

**Comment by xland** [comment]
能具体描述一下复现步骤吗？
是点击了哪个按钮进程无法退出呀？“复制到剪切板”、“保存成图片文件”、“直接退出”
AutoHotKey注册的什么快捷键？
有用到“钉住截图区域”的功能吗？
做了什么操作进程就会增加一个？

**Comment by xland** [comment]
未收到进一步反馈，先关了，有问题再开新的吧。
