### ISSUE TITLE
工具栏显示问题

### ISSUE THREAD

**Issue by wzhq1997** [xland/ScreenCapture#15]
1. 未正常显示：笔记本1080显示器，外接扩展4k显示器(150%缩放)；外接4k显示器全屏截图时工具栏正常在截图区域内显示，但笔记本屏幕全屏截图时，工具栏未显示出来。
2.  在1080屏幕上，工具栏大小、图标及文字感觉有点大，不知道是不是拉伸了，不过这个不是问题，不影响使用。

**Comment by xland** [comment]
问题1 已经在计划中了
问题2 这个还得在多考虑考虑再说要不要改
问题3 是窗口高亮导致的问题，这个也已经在计划中了

**Comment by xland** [comment]
问题1和问题3应该已经解决了
请下载新版本

**Comment by xland** [comment]
暂时先关了这个issue了，如果有问题，再开新的issue

**Comment by wzhq1997** [comment]
谢谢，前面准备反馈时github打不开了，看最新版本已经没有准备反馈的问了。TKS
