### ISSUE TITLE
建议贴图默认状态关闭编辑栏

### ISSUE THREAD

**Issue by chunlurenikun** [xland/ScreenCapture#17]
仅在鼠标悬浮或选中图片时开启

**Comment by xland** [comment]
这个我得考虑考虑

**Comment by chunlurenikun** [comment]
在拉取截图框时，没显示像素放大器

**Comment by xland** [comment]
拉截图框的过程中，为什么要看像素放大器呀？

**Comment by chunlurenikun** [comment]
> 拉截图框的过程中，为什么要看像素放大器呀？

这样在截图时更精确。本来在未拉取截图框时是有像素放大器，但在拉取过程中却没有显示

**Comment by xland** [comment]
嗯~你说的有道理，这个应该会做上去

**Comment by chunlurenikun** [comment]
> 嗯~你说的有道理，这个应该可以做上去

还有贴图能否置于其他应用窗口之上，毕竟主要用作记录

**Comment by xland** [comment]
嗯，这个应该也会做

**Comment by xland** [comment]
- 拉截图框的过程中，显示像素放大器
- 贴图窗口置于其他窗口之上

这两个建议已经优化掉了
请下载最新版本查看

**Comment by xland** [comment]
贴图窗口现在默认不显示工具栏了，
请下载最新版本
不过，我去掉了：“拖动选择截图区域时显示像素放大器” 这个功能
因为我在截图区域左上角显示了截图区域左上右下的坐标
