### ISSUE TITLE
不安装AutoHotKey，设置启动快捷键的方法

### ISSUE THREAD

**Issue by chunlurenikun** [xland/ScreenCapture#18]
创建一个快捷方式，放入C:\ProgramData\Microsoft\Windows\Start Menu\Programs目录中，右键快捷方式-属性-快捷键，就可以自定义启动快捷键了。不过在全屏播放视频或者游戏的时候快捷键会失效，但仍能通过win+s快捷键搜索[ScreenCapture](https://github.com/xland/ScreenCapture)使用

**Comment by chunlurenikun** [comment]
还有贴图能否置于其他应用窗口之上

**Comment by xland** [comment]
按下快捷键的时候系统会遍历快捷方式，找到对应的项之后再启动应用。
所以这种方法可能会比较慢（从按键到截图程序启动成功）
不知道的人还以为咱的截图程序启动比较慢呢
先把你这个Issue关啦，有问题再开新的。
