### ISSUE TITLE
截图框层级不够高 钉图不够完善几点问题

### ISSUE THREAD

**Issue by aDon0000** [xland/ScreenCapture#21]
1 截图: 截图框层级没有Ditto高
2 截图: 保存按钮 希望可以定义默认文件夹, 不用每次都选文件夹
3 钉图: 无法钉住时编辑栏无法隐藏, 希望可以滚轮改变大小

**Comment by xland** [comment]
第一个问题会尽快解决
后面两个都是不错的建议，我考虑一下就改

**Comment by xland** [comment]
问题1 应该已经解决了

**Comment by xland** [comment]
问题3也在最新版本里解决了

**Comment by xland** [comment]
第二个问题，现在都是用最后一次使用的文件夹。

最多能做到这样了，暂时不支持配置默认目录

这个ISSUE先关了，有好的建议再开新的
