### ISSUE TITLE
下方工具栏出到屏幕外了

### ISSUE THREAD

**Issue by silentmoooon** [xland/ScreenCapture#22]
![image](https://github.com/xland/ScreenCapture/assets/9210514/3dc9453a-57e5-436c-854d-7172a41056aa)

**Comment by xland** [comment]
确认BUG，现在就着手解决

**Comment by xland** [comment]
这个问题应该已经解决了，请下载最新版本
多谢反馈！

**Comment by silentmoooon** [comment]
哈哈,高效啊

**Comment by xland** [comment]
这个问题先关啦，有问题再开新Issue
