### ISSUE TITLE
好像还没有OCR功能? 考虑加一个不

### ISSUE THREAD

**Issue by silentmoooon** [xland/ScreenCapture#23]
好像还没有OCR功能? 考虑加一个不

**Comment by xland** [comment]
如果加到客户端，那么客户端的体积就会大不少。
如果用OCR服务，那么就得有一台服务器。

不管怎样，都会破坏简洁性，所以近期还不打算加这个OCR。
未来有好得方案会考虑得

**Comment by silentmoooon** [comment]
要不弄成客户端可选? 
比如第一次点ocr按钮才下载需要的资源, 或者readme加个另行下载的步骤 啥的.

**Comment by xland** [comment]
这到是可以，但从哪儿下载呢？我也没服务器~~~

**Comment by silentmoooon** [comment]
要不就放到release里边,让需要的用户手动下载吧,  直接在应用里边自己下载的话,估计很多没梯子的用户得下到猴年马月.
然后界面上，如果目录下没有对应的资源，也不显示对应按钮.

**Comment by xland** [comment]
越扯越远，以后再说吧

**Comment by xland** [comment]
如果你要自己做的话，可以试试这个库
https://github.com/tesseract-ocr/tesseract

**Comment by muwoo** [comment]
非常感谢 @xland 提供的开源截图工具。
@silentmoooon 我开发了一款 rubick 工具，集成了这个截图工具功能，ctrl+shift+A 快捷键可以快速使用，还可以安装orc插件使用截图orc功能哦：

rubick 官网：https://rubick.vip/

rubick 开源github 仓库：https://github.com/rubickCenter/rubick

![image](https://github.com/xland/ScreenCapture/assets/21073039/c1402e3f-3058-40e7-abc3-b738b6909722)

**Comment by silentmoooon** [comment]
> 如果你要自己做的话，可以试试这个库 https://github.com/tesseract-ocr/tesseract

cpp 实在不会,折腾了大半天,放弃了

**Comment by Pylogmon** [comment]
请问考虑和 [pot](https://github.com/pot-app/pot-desktop) 进行联动吗？

pot有相关的接口可以通过其他软件来调用。

**Comment by xland** [comment]
以后或许回吧

**Comment by xland** [comment]
各位，我暂时不考虑加入OCR了，
这个ISSUE先关了，
有问题再开新的ISSUE聊
谢谢大家的建议
