### ISSUE TITLE
屏幕左边缘截屏时候，截屏工具条被严重遮挡了

### ISSUE THREAD

**Issue by minshiwu** [xland/ScreenCapture#25]
如果在屏幕左边缘截屏时候，弹窗的截屏界面中，工具条被严重遮挡，无法使用；期望支持屏幕适应能力，特别影响使用，请优先解决。
由于公司网络限制，无法传图；相信作者应该明白我说的意思；

**Comment by xland** [comment]
你使用的时最新版本吗？
这个问题老版本确实存在，但新版本已经解决了
![image](https://github.com/xland/ScreenCapture/assets/2980915/1974ac69-fbb0-49fc-a46e-3cd505ba9356)
