### ISSUE TITLE
剪切框的大小不是窗口的实际显示大小

### ISSUE THREAD

**Issue by MAINCQ** [xland/ScreenCapture#28]
截取超出屏幕显示区域的窗口，会导致剪切框不能正确的包围窗口边缘。

![图片1](https://github.com/xland/ScreenCapture/assets/65262563/4c6ba95e-eb8f-4179-be62-f578f148ff3d)
> 图片中记事本被部分隐藏在窗口的右边缘内

### 错误原因
这个函数强制剪切框等于窗口的完整大小，而不是窗口的实际显示大小：
https://github.com/xland/ScreenCapture/blob/3eadbc38f9f44d79616f4b1393e5a21018d71a71/ScreenCapture/MainWinMask.cpp#L93

**Comment by xland** [comment]
谢谢反馈，这是个BUG，会尽快修复

**Comment by xland** [comment]
问题已经修复了，请下载最新版本测试

**Comment by MAINCQ** [comment]
测试了，新版本确实修复了这个问题
