### ISSUE TITLE
无法打开，提示系统字体加载失败

### ISSUE THREAD

**Issue by liangxyz** [xland/ScreenCapture#29]
如题，莫名其妙就不能用了，好奇怪。
更改兼容模式，使用管理员权限运行都一样
一直提示 系统字体加载失败

**Comment by xland** [comment]
请问是什么版本的操作系统
看看这个文件存在不？
`C:\\Windows\\Fonts\\simhei.ttf`

**Comment by xland** [comment]
我发了个新版本，应该能解决你的问题，可以下载下来试试看

**Comment by liangxyz** [comment]
> 请问是什么版本的操作系统 看看这个文件存在不？ `C:\\Windows\\Fonts\\simhei.ttf`

你好，这个字体文件竟然不存在，好奇怪，我的系统没有动过字体啊？

**Comment by xland** [comment]
这是系统中最常见的黑体
不明白你的电脑里为啥没这个字体文件
你用的是什么操作系统呀，具体的版本号是啥？
![image](https://github.com/xland/ScreenCapture/assets/2980915/690f0a2e-83fe-4d41-afad-6a0cd75190da)

**Comment by liangxyz** [comment]
谢谢，我自己下了一个字体就好了。我用的25398.1 win11 系统，主要是没动过字体的东西呀

**Comment by xland** [comment]
谢谢反馈，我找机会试试win11系统
你以前在win11下成功运行过咱这个截图软件不？

**Comment by liangxyz** [comment]
> 谢谢反馈，我找机会试试win11系统 你以前在win11下成功运行过咱这个截图软件不？

你好，就是成功运行过，然后莫名其妙就不能运行了，才知道是因为缺少了字体

**Comment by liangxyz** [comment]
> 谢谢反馈，我找机会试试win11系统 你以前在win11下成功运行过咱这个截图软件不？

你好，就是成功运行过，然后莫名其妙就不能运行了，才知道是因为缺少了字体

**Comment by 0x738A** [comment]
![image](https://github.com/xland/ScreenCapture/assets/43438471/7af35d5f-b34f-4afc-9b0c-ceb195293d56)
打不开

**Comment by xland** [comment]
@0x738A 
你也没这个字体吗？C:\\Windows\\Fonts\\simhei.ttf
Win11系统？

**Comment by 0x738A** [comment]
> @0x738A 你也没这个字体吗？C:\Windows\Fonts\simhei.ttf Win11系统？

没有
![image](https://github.com/xland/ScreenCapture/assets/43438471/a78af4a6-e08b-4c06-b460-52e247834dc3)

**Comment by 0x738A** [comment]
请问能提供一个不依赖vc运行时库的版本么

**Comment by xland** [comment]
这样看字体文件，是找不到simhei.ttf的
最好用everything找
![image](https://github.com/xland/ScreenCapture/assets/2980915/3e4e8258-bf8d-4b7d-8619-5d49840b6125)
不过，你看上去用的是英文操作系统，那没这个中文字体可能也正常
我在这里传一个，你把这个字体文件放到这个目录下应该就可以了
[simhei.zip](https://github.com/xland/ScreenCapture/files/13454444/simhei.zip)

另外，字体文件根VC运行库没啥关系呀，
你那边还报了其他与VC运行库有关的错误吗？

**Comment by 0x738A** [comment]
> 这样看字体文件，是找不到simhei.ttf的 最好用everything找 ![image](https://user-images.githubusercontent.com/2980915/285335100-3e4e8258-bf8d-4b7d-8619-5d49840b6125.png) 不过，你看上去用的是英文操作系统，那没这个中文字体可能也正常 我在这里传一个，你把这个字体文件放到这个目录下应该就可以了 [simhei.zip](https://github.com/xland/ScreenCapture/files/13454444/simhei.zip)
> 
> 另外，字体文件缺失与VC运行库没啥关系呀， 你那边还报了其他与VC运行库有关的错误吗？

建议你把字体换为segoeui，或者把字体作为资源文件，然后用“AddFontMemResourceEx”从资源文件加载字体，这样即使别人的电脑上没有simhei字体也可以正常使用。
编译release版本的时候，使用/MT选项可以使兼容性更好，在没有安装运行时库的电脑上也可以运行

**Comment by xland** [comment]
这两个工作都会使产物变大，成本和收益值得考虑。

**Comment by 0x738A** [comment]
> 这两个工作都会使产物变大，成本和收益值得考虑。

用upx压缩一下。程序都无法运行，再小巧精致也没意义诶。（可以上传一下Blend2D的lib么）

**Comment by xland** [comment]
blend2d有cmake配置，自己编吧，不麻烦的

**Comment by xland** [comment]
最新版V2.0.7已更换了默认字体，应该不存在此问题了，暂时先关了这个issue，有问题再开新的issue
