### ISSUE TITLE
功能建议：读取剪切板图片并钉图、使用启动参数钉图

### ISSUE THREAD

**Issue by jiabaoyu** [xland/ScreenCapture#30]
1. 读取剪切板图片并钉图，这样钉图就可以不仅限于刚截的图了
2. 使用启动参数钉图，比如 "D:\path\to\ScreenCapture.exe --ding"，可以用于ahk一键调用钉图功能，是上一个建议的延申

**Comment by xland** [comment]
嗯，听上去不错~先记下来

**Comment by xland** [comment]
@jiabaoyu 

https://github.com/xland/ScreenCapture/releases/tag/2.1.5

这个版本，用这个命令行参数：`ScreenCapture.exe --pin:clipboard`
直接把剪切板里的图片钉在桌面上。

**Comment by jiabaoyu** [comment]
2.1.5的贴图运行参数完美使用了！
