### ISSUE TITLE
 希望可以把功能框做小一点

### ISSUE THREAD

**Issue by kkkkkkmoji** [xland/ScreenCapture#33]
希望可以把功能框做小一点，感觉现在的功能框太大了，wx大小的功能框感觉好一些。

**Comment by JohnChan1017** [comment]
1080p的屏幕，菜单栏超级大，作者是在4k分辨率的屏幕下进行开发吗？求个1080p版本T_T

**Comment by xland** [comment]
1080p分辨率下很大吗？
能不能截个图给我看看
别忘了截图里最好有个参照物
比如：

![image](https://github.com/xland/ScreenCapture/assets/2980915/fd50f234-d038-4b7e-9f11-8f79050ea14a)

**Comment by kkkkkkmoji** [comment]
感谢回答，请看
![ScreenCapture](https://github.com/xland/ScreenCapture/assets/148427163/f917ceb2-c928-4b09-ba21-b401fda097ea)

**Comment by kkkkkkmoji** [comment]
与vx对比
![vx](https://github.com/xland/ScreenCapture/assets/148427163/b54d5b97-3b7f-4ecd-a031-125c10f64340)

**Comment by xland** [comment]
可能微信做了分辨率的适配
不过我感觉差不太多呀，你看微信在4K屏下的工具栏（比咱们的大多了）

下图是在同一个屏幕下的截图（先启动咱们的截图，再启动微信截图）
![image](https://github.com/xland/ScreenCapture/assets/2980915/9203f28e-c515-477f-baee-0641d3d9a274)

**Comment by kkkkkkmoji** [comment]
不懂适配，只是提个issue，总之感谢你的开发
![盖中盖中盖](https://github.com/xland/ScreenCapture/assets/148427163/bb4755cc-ff8d-40aa-b989-2ad8ba483691)

**Comment by xland** [comment]
先留着你这个issue，等后面重构时再考虑要不要优化

**Comment by kli2013** [comment]
我也希望能小一点，加个票

**Comment by xland** [comment]
@kli2013 @kkkkkkmoji @JohnChan1017 

这个问题在最新版V2.0.7中已经修复了
