### ISSUE TITLE
优化ScreenCapture启动了多个实例

### ISSUE THREAD

**Issue by wcctml** [xland/ScreenCapture#38]
https://github.com/xland/ScreenCapture/issues/14

关于这个问题，上面链接提到的问题，应该是快捷键触发了多次。看了Main函数入口并没有限制只能启动多个示例。

代码可以这样优化

`

int APIENTRY wWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE hPrevInstance, _In_ LPTSTR lpCmdLine, _In_ int nCmdShow)
{
    //判断只能启动一个实例
    HANDLE hMutex = CreateMutex(NULL, TRUE, _T("ScreenCapture"));
    if (GetLastError() == ERROR_ALREADY_EXISTS)
    {
        CloseHandle(hMutex);
        return -1;
    }
    Font::Init();
    new MainWin();
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0))
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }
    Font::Dispose();
    auto code = MainWin::GetQuitCode();
    CloseHandle(hMutex);
    return code;
}

`

作者看看。

**Comment by xland** [comment]
谢谢，下个版本（基于Skia）我会把单实例进程锁加上。

**Comment by xland** [comment]
这个单进程锁加不了，很多人都是钉图之后，再启动一个截图

**Comment by xland** [comment]
先关了这个issue了，如果有意见咱们开新issue，再讨论
