### ISSUE TITLE
对于新版本(2.02)有2个问题

### ISSUE THREAD

**Issue by kli2013** [xland/ScreenCapture#39]
第一个是程序大小忽然暴增,虽然还是很小,但是还是挺敏感的,对比1.0增大2倍多

第二个是不能连续启动多个实例,钉完一个截图画面不能再次启动钉另外的画面

**Comment by xland** [comment]
第一个问题：因为渲染引擎从Blend2d切换成了Skia，所以变大了......也变强了...
第二个问题：我稍后会改掉。

**Comment by kli2013** [comment]
欧德k
谢谢

**Comment by xland** [comment]
第二个问题应该已经解决了，请下载最新版本
