### ISSUE TITLE
blend2d编译时报错，createFromData多了一个参数

### ISSUE THREAD

**Issue by ruomeng0x** [xland/ScreenCapture#4]
branch：blend2d 分支的最新代码 
commit: 0badaeb13ced93ad717de198a408cd174afd0ba2
error: 错误	C2664	“BLResult BLImage::createFromData(int,int,BLFormat,void *,intptr_t,BLDestroyExternalDataFunc,void *) noexcept”: 无法将参数 6 从“BLDataAccessFlags”转换为“BLDestroyExternalDataFunc”	ScreenCapture	

将下图中的两个标红处删去即可正常编译运行

![image](https://github.com/xland/ScreenCapture/assets/66309950/ef042886-5286-4f97-b3ae-5c7a9b52dbc4)

**Comment by xland** [comment]
收到，我可能要周末看

**Comment by xland** [comment]
#6
