### ISSUE TITLE
[bug] 2.0.3 preview 无法在原马赛克的基础上继续绘画

### ISSUE THREAD

**Issue by Mikachu2333** [xland/ScreenCapture#40]
如题。

修改建议：
双击某模式的图标以后进入“仅更改以往元素大小”的模式，例如在马赛克模式的图标上点两次，此时不能绘画只能修改大小，正常模式下不自动进入修改大小的模式，只能绘画

此外，当前版本还有一个问题就是无法在已绘画的区域继续绘画（例如马赛克后在该区域继续添加色块等）
 
![图片](https://github.com/xland/ScreenCapture/assets/63829496/54e8c851-d358-4f09-8e38-dade0821f0fb)

**Comment by xland** [comment]
嗯，这是个问题，但交互方式还值得考虑一下

**Comment by xland** [comment]
现在的交互方式为：

鼠标移入某个历史元素所在区域后，等待1.6秒，该元素才会进入编辑状态.

**Comment by Mikachu2333** [comment]
好！！！

不过发现马赛克功能还是有点奇怪的问题，增加一点建议就是只能在同一功能下编辑同一功能的东西

https://github.com/xland/ScreenCapture/assets/63829496/47de06d0-fc75-44dd-9940-3275bc2a2adc

**Comment by xland** [comment]
这是个问题
我应该会从根源上解决这个问题。

**Comment by xland** [comment]
问题应该已经解决了，请下载最新版本
