### ISSUE TITLE
解决编译问题

### ISSUE THREAD

**Issue by wcctml** [xland/ScreenCapture#41]
CMakeLists.txt
第一行需要加上opengl32 
加上第二行指定程序入口函数

```
    TARGET_LINK_LIBRARIES(ScreenCapture skia Dwmapi winmm kernel32 user32 shell32 imm32 opengl32)
    set_target_properties(ScreenCapture PROPERTIES WIN32_EXECUTABLE TRUE)
```

**Comment by xland** [comment]
这个程序目前还都是软渲染，没用到OPENGL呀。

**Comment by wcctml** [comment]
我这边看是skia库使用了。 😃  可能是版本问题，可以关掉了
`
x64-Debug\skia.lib(gpu.GrGLMakeNativeInterface_win.obj) : error LNK2019: 无法解析的外部符号 __imp_wglGetProcAddress，函数 "class sk_sp<struct GrGLInterface const > __cdecl GrGLMakeNativeInterface(void)" (?GrGLMakeNativeInterface@@YA?AV?$sk_sp@$$CBUGrGLInterface@@@@XZ) 中引用了该符号
`

**Comment by xland** [comment]
嗯，以后我会考虑加上硬件加速的能力，
目前先把这个issue关了
