### ISSUE TITLE
[bug] 橡皮擦擦不掉最后一个绘图

### ISSUE THREAD

**Issue by wcctml** [xland/ScreenCapture#42]
1、如下图，最后一个箭头擦不掉，然后再添加一个箭头的时候就被刷掉了。

![test](https://github.com/xland/ScreenCapture/assets/13461698/c2757e8d-390b-4c2a-a85a-a28365f3a00e)

**Comment by xland** [comment]
嗯，多谢反馈，稍后处理

**Comment by xland** [comment]
这个问题应该已经解决了，请下载最新版本
