### ISSUE TITLE
两个功能建议

### ISSUE THREAD

**Issue by wisenut2009** [xland/ScreenCapture#43]
非常好的工具，谢谢！

两个功能建议：
1）支持按控件截图。
2）支持快捷键，比如：Ctrl+S用于保存，Ctrl+C用于保存到剪贴板。

**Comment by xland** [comment]
谢谢反馈
第二点会尽快加上
第一点要考虑一下

**Comment by xland** [comment]
第二点已经加上了，请下载最新版本

**Comment by wisenut2009** [comment]
速度真快！谢谢！

**Comment by Mikachu2333** [comment]
请问钉图有计划退出快捷键吗

**Comment by xland** [comment]
@Mikachu2333 
退出钉图窗口是有快捷键的：Esc

你是说按快捷键直接钉图吗？
Ctrl+P如何？
P是Pin的首字母

**Comment by xland** [comment]
@wisenut2009 

控件截图，
这个我暂时不打算做了
因为有些人不喜欢这个功能（对于控件很多的窗口，会干扰用户操作）
而我暂时还没打算给ScreenCapture提供配置文件（关闭控件j截图能力）

**Comment by wisenut2009** [comment]
能理解。有人不喜欢，也会有人喜欢的，就看您对于软件和目标用户的构想了。



 
发件人： liulun
发送时间： 2024-01-18 18:43
收件人： xland/ScreenCapture
抄送： wisenut2009; Mention
主题： Re: [xland/ScreenCapture] 两个功能建议 (Issue #43)
@wisenut2009
控件截图，
这个我暂时不打算做了
因为有些人不喜欢这个功能（对于控件很多的窗口，会干扰用户操作）
而我暂时还没打算给ScreenCapture提供配置文件（关闭控件j截图能力）

**Comment by Mikachu2333** [comment]
> 你是说按快捷键直接钉图吗？
> Ctrl+P如何？
> P是Pin的首字母

可以的，不过推荐在软件编辑栏的按钮上加上提示，这样好一点
现在都是软件默认的快捷键，普通用户很难知道啊

**Comment by Mikachu2333** [comment]
> > 你是说按快捷键直接钉图吗？
> > Ctrl+P如何？
> > P是Pin的首字母
> 
> 可以的

不过如果从方便快捷的角度来说，我推荐ctrl+d，距离近，D可以看作Ding图的缩写

**Comment by xland** [comment]
Ctrl+P了，咱得国际化。嘿

**Comment by xland** [comment]
提示下个版本会加上

**Comment by xland** [comment]
提示在最新版本中加上了
