### ISSUE TITLE
在Win7上有些Bug

### ISSUE THREAD

**Issue by wisenut2009** [xland/ScreenCapture#44]
运行后不能截图，也不能按Esc取消，只能从任务管理器中结束进程。这个现象出现了一次，没能复现，但发现Windows任务栏图标显示混乱。
![image](https://github.com/xland/ScreenCapture/assets/36567301/0b12ec65-b16d-4ce1-bd09-63094e3b3aef)
软件工具条的图标显示不正确，但想了想，可能跟我采用MacType将字体替换成了自制字体有关，退出MacType后重试是正常的。不过这些图标是不是可以作为资源打包到exe里？

**Comment by wisenut2009** [comment]
了解，Win7是我的主力机 ⊙﹏⊙‖∣，这么好的软件用不了

**Comment by xland** [comment]
暂时先不准备支持Win7了
