### ISSUE TITLE
希望增加一些快捷键以增强功能

### ISSUE THREAD

**Issue by Mikachu2333** [xland/ScreenCapture#47]
1. 希望增加一个复制到剪贴板同时保存到文件的功能
看了代码，发现因为 `App::Quit(7);` 没法直接复用，只能另开一个函数就没提pr（业余爱好cpp，只会用笨办法改……）

**Comment by xland** [comment]
我大概能理解你的需求，但有这需求的人多吗？
要做这个功能，恐怕要在工具栏上多加一个按钮

**Comment by Mikachu2333** [comment]
其实感觉只加一个快捷键即可

至于工具栏，我的建议是直接在剪贴板的按钮下面加一行快捷键的提示即可

另，pin并保存也有这个需求

此外，发现复制到剪贴板完了会以bmp的格式储存，能不能把bmp换成png或者jpg格式以方便查看？bmp格式现在比较少见了，并且很多软件不支持

**Comment by Mikachu2333** [comment]
> 我大概能理解你的需求，但有这需求的人多吗？

大概就是编辑了图片以后直接复制到剪贴板，结果后来发现不妥，需要继续改改……所以需要同时保存到文件以保证自己不会重新做一遍之前的步骤

另，感觉可以在快捷键上鼓捣点东西，例如在ctrl+s的基础上加一个alt+s直接保存到软件目录，其他的需求（例如刚刚提的这俩）也可以搞一个这种快捷键，以alt取代ctrl，使得各类截图省略弹窗，直接保存到软件所在的目录下

这样ctrl与alt两套快捷键，互不干扰，功能也都有，就是写起来麻烦 😢

**Comment by Mikachu2333** [comment]
一个外包装程序的雏形：
https://github.com/Mikachu2333/sc_starter

**Comment by Mikachu2333** [comment]
> 此外，这里是一个外包装程序的雏形： https://github.com/Mikachu2333/sc_starter
> 
> 后续如果本体不支持自定义启动快捷键的话我可能会加自定义快捷键和托盘试试

自定义快捷键功能已经推出。

**Comment by Mikachu2333** [comment]
看了看，暂时close掉吧，我继续更我那边的就是了。

期待作者继续继续增加一些可供自定义的args，我也会尽量往我那个补丁程序里面加的 😃

**Comment by xland** [comment]
@Mikachu2333 ，最近忙的，好几个问题都没来得及处理
