### ISSUE TITLE
做个图标？

### ISSUE THREAD

**Issue by skywind3000** [xland/ScreenCapture#5]
光秃秃的，快捷方式放桌面也不好看。

**Comment by xland** [comment]
不过我建议你使用Readme里说的AutoHotKey来做截图的热键，而不是用图标快捷方式启动

**Comment by skywind3000** [comment]
我就是不喜欢驻留和右下角图标才喜欢用这类一次性运行的截图工具，
ahk 又搞出一个图标来，和其他截图没区别了。

**Comment by xland** [comment]
嗯，做个图标还是相当有必要的。

**Comment by xland** [comment]
图标已经做好了
请下载新版本

**Comment by skywind3000** [comment]
多谢 👍
