### ISSUE TITLE
拉取代码编译运行的程序不能适配高清屏多屏

### ISSUE THREAD

**Issue by wcctml** [xland/ScreenCapture#52]
如下图右侧第二屏幕最右区域因为DPI不同不能截全屏幕内容。
请问是skia库的问题？还是需要做什么配置？

![image](https://github.com/xland/ScreenCapture/assets/13461698/71c784e6-e34f-4761-841e-bada68983995)

**Comment by xland** [comment]
自己编译的不行，在release页面下载的可以吗？

**Comment by wcctml** [comment]
Release页面下载的可以。

我使用skia也是122

**Comment by xland** [comment]
你看看这个配置设置好了没？
![image](https://github.com/xland/ScreenCapture/assets/2980915/27d09e9a-6094-4623-b937-5b3ae829558c)

**Comment by wcctml** [comment]
解决了，我之前使用VS2022直接运行的项目不行。

现在CMake生成工程文件才会自动配置好。
