### ISSUE TITLE
上下左右宽高支持参数调用多语言显示

### ISSUE THREAD

**Issue by wzhq1997** [xland/ScreenCapture#53]
谢谢作者，不知道是否可以支持代码调用截图时【上下左右宽高】等提示信息可以参数设置多语言显示，比如传入cn中文，en英文。

**Comment by xland** [comment]
嗯，我考虑一下

**Comment by xland** [comment]
发了新版本，现在支持多语言了。

https://github.com/xland/ScreenCapture/releases/tag/2.1.6

**Comment by xland** [comment]
先关了，有问题再开新的。
