### ISSUE TITLE
看main分支里还有类似QFontDatabase、QtWidgets，是否还依赖QT？

### ISSUE THREAD

**Issue by oohusl** [xland/ScreenCapture#69]

**Comment by xland** [comment]
你看下readme里第一句话

**Comment by oohusl** [comment]
看到了。另sdk/skia需要自己编译，还是有地址可下载？

**Comment by duhbbx** [comment]
这个截图功能好强大

第一句话是啥？我想也自己编译玩下

**Comment by oohusl** [comment]
> 这个截图功能好强大
> 
> 第一句话是啥？我想也自己编译玩下

第一句是当前发布版本是2.1.*分支，skia搞定了吗？

**Comment by duhbbx** [comment]
> > 这个截图功能好强大
> > 第一句话是啥？我想也自己编译玩下
> 
> 第一句是当前发布版本是2.1.*分支，skia搞定了吗？

我就是没看懂这句话，和你的提问的关联关系 ><

> 看main分支里还有类似QFontDatabase、QtWidgets，是否还依赖QT

**Comment by xland** [comment]
skia搞定了呀
稳定分支就是Skia搞的
