### ISSUE TITLE
建议:  鼠标悬停显示button details 

### ISSUE THREAD

**Issue by BingyuanZZZ** [xland/ScreenCapture#9]
当用户截图后，用户不知道button的作用，对于使用者来说十分不友好，建议当鼠标悬停在某一button时候，显示button的详细信息（e.g.: 当 鼠标悬停文字工具显示文字工具提示）

**Comment by xland** [comment]
谢谢建议，已列入计划列表

**Comment by xland** [comment]
这个功能已经添加到最新版本中了
请下载最新版本
有问题提新的issue，这个先关啦
